-- We can not insert a data in child table without taking permission of parent table
-- Whatever information you want to inserta in a child table if that information not available in parent table
-- Then we can not insert that information in childe table
-- If you want to insert a data in child table directly then we have to disabled the foreign key by 
-- SET FOREIGN_KEY_CHECKS = 0 [OFF] & SET FOREIGN_KEY_CHECKS = 1 [ON]
CREATE TABLE A1(
DEPARTMENT_ID INT UNSIGNED PRIMARY KEY,
DEPARTMENT_NAME VARCHAR(50));

CREATE TABLE B1(
EMP_ID INT UNSIGNED PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
SALARY DECIMAL(10,2),
DEPARTMENT_ID INT UNSIGNED,
CONSTRAINT B1_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES A1 (DEPARTMENT_ID));

SELECT COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_COLUMN_NAME, REFERENCED_TABLE_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'B1';

INSERT INTO B1 VALUES(100, 'ANAND', 'JAGDALE', 25000, 99);

-- 14:06:56	INSERT INTO B1 VALUES(100, 'ANAND', 'JAGDALE', 25000, 99)	Error Code: 1452. Cannot add or update a child row: a foreign key constraint fails (`hr`.`b1`, CONSTRAINT `B1_FK` FOREIGN KEY (`DEPARTMENT_ID`) REFERENCES `a1` (`DEPARTMENT_ID`))	0.016 sec

SET FOREIGN_KEY_CHECKS = 0
 
INSERT INTO B1 VALUES(100, 'ANAND', 'JAGDALE', 25000, 99);
SELECT * FROM B1;

SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO B1 VALUES(101, 'VEDPRAKASH', 'ARYA', 25000, 94);
SELECT * FROM B1;

ALTER TABLE B1 DROP CONSTRAINT B1_FK;
SELECT COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_COLUMN_NAME, REFERENCED_TABLE_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'B1';

ALTER TABLE B1 ADD CONSTRAINT B1_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES A1(DEPARTMENT_ID);
-- 14:30:54	ALTER TABLE B1 ADD CONSTRAINT B1_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES A1(DEPARTMENT_ID)	Error Code: 1452. Cannot add or update a child row: a foreign key constraint fails (`hr`.`#sql-7d0_31`, CONSTRAINT `B1_FK` FOREIGN KEY (`DEPARTMENT_ID`) REFERENCES `a1` (`DEPARTMENT_ID`))	0.297 sec

-- CHECK CONSTRAINT [Used for checking particular value from specific column of table]
-- System always stored check constraint by name
-- We can give other name to check constraint

-- 1ST METHOD:-
CREATE TABLE A2(
EMP_ID INT UNSIGNED,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
AGE INT CHECK (AGE > 14),
JOB_ID VARCHAR(50),
DEPARTMENT_ID INT UNSIGNED);

ALTER TABLE A2 ADD COLUMN SALARY DECIMAL(10,2) AFTER AGE;
DESC A2;

INSERT INTO A2 VALUES(100, 'ANAND', 'JAGDALE', 13,10000, 'IT_PROG', 96);
-- 14:58:20	INSERT INTO A2 VALUES(100, 'ANAND', 'JAGDALE', 13, 'IT_PROG', 96)	Error Code: 3819. Check constraint 'a2_chk_1' is violated.	0.000 sec

INSERT INTO A2 VALUES(100, 'ANAND', 'JAGDALE', 25, 25000, 'DATA_SCIENTIST', 96);
SELECT * FROM A2;

-- 2ND METHOD:-
CREATE TABLE A3(
EMP_ID INT UNSIGNED,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
AGE INT UNSIGNED,
SALARY DECIMAL(10,2),
JOB_ID VARCHAR(50),
DEPARTMENT_ID INT UNSIGNED,
CONSTRAINT AGE_CHK CHECK (AGE >14));

INSERT INTO A3 VALUES(100, 'ANAND', 'JAGDALE', 25, 25000, 'IT_PROG', 96);
SELECT * FROM A3;

-- 3RD METHOD:-
CREATE TABLE A4(
EMP_ID INT UNSIGNED,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
AGE INT UNSIGNED,
SALARY DECIMAL(10,2),
JOB_ID VARCHAR(50),
DEPARTMENT_ID INT UNSIGNED);

ALTER TABLE A4 ADD CONSTRAINT AGE_CHECK CHECK (AGE > 14);

INSERT INTO A4 VALUES(100, 'NARSIMHA', 'REDDY', 19, 12000, 'OFFICE_BOY', 08);
SELECT * FROM A4;

