-- TRIGGER:- 
-- Its create in DML statement (INSERT | UPDATE | DELETE)
-- It can created twice either BEFOR inserting a data point & AFTER inserting a some data points for newly inserting  data point
-- It can create for already existed table but it works only tracking the missing data point by log window
-- One trigger for one column means one table containing a no. of trigger because we can create a trigger for no. of columns

-- BEFORE:-
CREATE TABLE CUSTOMERS(
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
AGE INT);

DELIMITER //
CREATE TRIGGER VERIFY_AGE
BEFORE INSERT ON CUSTOMERS FOR EACH ROW
BEGIN
IF NEW.AGE <0 THEN SET NEW.AGE = 0;
ELSEIF NEW.AGE IS NULL THEN SET NEW.AGE = 0;
END IF;
END //
DELIMITER ;

INSERT INTO CUSTOMERS VALUES
('ANAND', 'JAGDALE', 25),
('RATNADEEP', 'MITKARI', -25),
('RAVIKUMAR', 'MHETRE', 28),
('KARAN', 'PATIL', 27),
('DINESH', 'MORE', NULL);

SELECT * FROM CUSTOMERS;

-- AFTER:-
DROP TABLE STUDENTS;
CREATE TABLE STUDENTS(
ID INT PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
AGE INT,
BIRTHDATE DATE);

DROP TABLE LOG;
CREATE TABLE LOG(
ID INT AUTO_INCREMENT,
PERSON_ID INT,
MESSAGE TEXT NOT NULL,
PRIMARY KEY (ID, PERSON_ID));

DROP TRIGGER VERIFY_BIRTHDATE;
DELIMITER //
CREATE TRIGGER VERIFY_BIRTHDATE
AFTER INSERT ON STUDENTS FOR EACH ROW
BEGIN
IF NEW.BIRTHDATE IS NULL THEN
INSERT INTO LOG(PERSON_ID, MESSAGE) VALUES (NEW.ID, CONCAT('HEY', ' ', NEW.FIRST_NAME, ' ', 'PLEASE PROVIDE YOUR BIRTHDATE'));
END IF;
END //
DELIMITER ;

INSERT INTO STUDENTS VALUES
(101, 'ANAND', 'JAGDALE', 25, '1996-10-30'),
(102, 'DINESH', 'MORE', 26, NULL),
(103, 'RAVIKUMAR', 'MHETRE', 28, '1994-02-25'),
(104, 'KARAN', 'PATIL', 27, '1995-12-03'),
(105, 'SAUDUL', 'HODA', 24, NULL);

SELECT * FROM STUDENTS;
SELECT * FROM LOG;
